### ISSUE TITLE
配置AzureOpenAI启动时，自定义模型无效

### ISSUE THREAD

**Issue by WJZ-P** [AIDotNet/OpenDeepWiki#79]
**Describe the bug**
我使用mac系统启动，下面是我的具体配置：
docker-compose-arm.yml

```
services:
  koalawiki:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/koala-wiki:arm64
    environment:
      - KOALAWIKI_REPOSITORIES=/repositories
      - TASK_MAX_SIZE_PER_USER=5 # 每个用户AI处理文档生成的最大数量
      - REPAIR_MERMAID=1 # 是否进行Mermaid修复，1修复，其余不修复
      - CHAT_MODEL=gpt-4o # 必须要支持function的模型
      - ANALYSIS_MODEL=gpt-4o # 分析模型，用于生成仓库目录结构，这个很重要，模型越强，生成的目录结构越好，为空则使用ChatModel
      # 分析模型建议使用GPT-4.1  , CHAT模型可以用其他模型生成文档,以节省 token 开销
      - CHAT_API_KEY=xxxx #您的APIkey
      - LANGUAGE= # 设置生成语言默认为“中文”, 英文可以填写 English 或 英文
      - ENDPOINT=x x x x x
      - DB_TYPE=sqlite
      - MODEL_PROVIDER=AzureOpenAI # Model provider, default is OpenAI, supports AzureOpenAI and Anthropic
      - DB_CONNECTION_STRING=Data Source=/data/KoalaWiki.db
      - UPDATE_INTERVAL=5 # 仓库增量更新间隔，单位天
      - EnableSmartFilter=true # 是否启用智能过滤，这可能影响AI得到仓库的文件目录
      - PARALLEL_COUNT=1 # The warehouse processes the quantity inparallel
      - ENABLE_INCREMENTAL_UPDATE=true # 是否启用增量更新s
    volumes:
      - ./repositories:/app/repositories
      - ./data:/data
    build:
      context: .
      dockerfile: src/KoalaWiki/Dockerfile
      
  koalawiki-web:
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/koala-wiki-web:arm64
    environment:
      - NEXT_PUBLIC_API_URL=http://koalawiki:8080 # 用于提供给server的地址
    build:
      context: ./web
      dockerfile: Dockerfile
      
  nginx: # 需要nginx将前端和后端代理到一个端口
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/nginx:alpine
    platform: linux/amd64   #解决 M芯片 Mac 启动失败的问题
    ports:
      - 8090:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - koalawiki
      - koalawiki-web

```

我启动项目后输入url进行分析，在koalawiki的log中报错如下：
```
[04:37:03 ERR] HTTP POST [https://tm-deepwiki-eu2.openai.azure.com/openai/deployments/DeepSeek-V3/chat/completions?api-version=2025-03-01-preview⁠](https://tm-deepwiki-eu2.openai.azure.com/openai/deployments/DeepSeek-V3/chat/completions?api-version=2025-03-01-preview) => 404 in 1979ms, Error: NOT FOUND

[04:37:03 ERR] 发生错误：System.ClientModel.ClientResultException: Service request failed.

Status: 404 (Not Found)


   at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)

   at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)......
```

可以看到这里后台请求的URL在我配置了模型为gpt-4o的情况下，依然调用了deepseek-v3，导致出错。

**To Reproduce**
同上

**Expected behavior**
正常生成

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac os 15

**Smartphone (please complete the following information):**

**Additional context**
